name: CI

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "master"
  pull_request:
    workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true


jobs:
  ci:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: smallstep/workflows/.github/workflows/goCI.yml@main
    with:
      run-codeql: true
    secrets: inherit
